/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizapp.gui;

/**
 *
 * @author jp
 */
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import quizapp.dao.PerformanceDAO;
import quizapp.dao.resultAnalysis;
import quizapp.pojo.StudentAnalysis;
import quizapp.pojo.UserProfile;
public class PredictionAnalysis extends javax.swing.JFrame {

    private String userid;
    private String examid;
    ArrayList<resultAnalysis> rst=null;
    ArrayList<Double> per=null;
    private String subject;
    private int preparationValueSet=0;
    private int AccuracyValueSet=0;
 
    /**
     * Creates new form PredictionAnalysis
     */
    public PredictionAnalysis() {
       
       
        initComponents();
         setResizable(false);
        this.setLocationRelativeTo(null);
        
        
       
    }

    

    PredictionAnalysis(Object userid, Object subject,Object examid) {
       this();
       this.userid=(String)userid;
       this.examid=(String)examid;
       this.subject=(String)subject;
       setCurrentStatus();
       setPredictedStatus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtHelloMsg = new javax.swing.JLabel();
        btnbargraph = new javax.swing.JButton();
        btnchart = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAccuracy1 = new javax.swing.JLabel();
        lblpreparation1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblprogress1 = new javax.swing.JLabel();
        lblAccuracy2 = new javax.swing.JLabel();
        lblpreparation2 = new javax.swing.JLabel();
        lblprogress2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(52, 137, 223));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Prediction Analysis ");

        txtHelloMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHelloMsg.setForeground(new java.awt.Color(255, 255, 255));
        txtHelloMsg.setText("Hello ");
        txtHelloMsg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnbargraph.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnbargraph.setText("Bar graph Analysis");
        btnbargraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbargraphActionPerformed(evt);
            }
        });

        btnchart.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnchart.setText("Pie Chart Analysis");
        btnchart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchartActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("current Accuracy %");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("preparation level");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("progress level");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Present Status");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Predicted Status");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Predicted Accuracy %");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("preparation level");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("progress level");

        lblAccuracy1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAccuracy1.setForeground(new java.awt.Color(0, 0, 51));
        lblAccuracy1.setText("50%");

        lblpreparation1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblpreparation1.setForeground(new java.awt.Color(0, 0, 51));
        lblpreparation1.setText("50%");

        lblprogress1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblprogress1.setForeground(new java.awt.Color(0, 0, 51));
        lblprogress1.setText("50%");

        lblAccuracy2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAccuracy2.setForeground(new java.awt.Color(0, 0, 51));
        lblAccuracy2.setText("50%");

        lblpreparation2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblpreparation2.setForeground(new java.awt.Color(0, 0, 51));
        lblpreparation2.setText("50%");

        lblprogress2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblprogress2.setForeground(new java.awt.Color(0, 0, 51));
        lblprogress2.setText("50%");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtHelloMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnchart, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(btnbargraph, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblpreparation1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblprogress1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblAccuracy1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprogress2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccuracy2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpreparation2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHelloMsg)
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnchart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbargraph, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAccuracy1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAccuracy2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblpreparation2))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblpreparation1)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprogress2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprogress1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbargraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbargraphActionPerformed
       try{
        ArrayList<StudentAnalysis> st=PerformanceDAO.getStudentResult(userid);
        if(st.isEmpty()){
               JOptionPane.showMessageDialog(null,"No test given by :"+UserProfile.getUsername(),"Message",JOptionPane.INFORMATION_MESSAGE);
            return;
           }
      
        DefaultCategoryDataset dset=new DefaultCategoryDataset(); 
       for(StudentAnalysis s:st)
        {
        dset.setValue(s.getPercentage(),"precentage",s.getTestid());
       }
       
        JFreeChart bch=ChartFactory.createBarChart("Student Test-Wise Analysis","test","percentage", dset, PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot cplot=bch.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.BLUE);
        ChartFrame fm=new ChartFrame("Student Test-Wise Analysis",bch);
        fm.setSize(550,550);
        fm.setResizable(false);
        fm.setLocationRelativeTo(null);
      
      fm.setVisible(true);
         }catch(SQLException ex){
               JOptionPane.showMessageDialog(null,"SQL Error"+ex,"Error!",JOptionPane.ERROR_MESSAGE);
           }
        
    }//GEN-LAST:event_btnbargraphActionPerformed

    private void btnchartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchartActionPerformed
       //try{
        // ArrayList<resultAnalysis> rst=PerformanceDAO.getStudenttestresult(userid,examid);
        System.out.println("hello jp1");
        if(rst.isEmpty()){
               JOptionPane.showMessageDialog(null,"No test given by :"+userid,"Message",JOptionPane.INFORMATION_MESSAGE);
                 System.out.println("hello jp2");
            return;
           }
        System.out.println("hello jp3");
        DefaultPieDataset Dpie=new DefaultPieDataset();
       for(resultAnalysis s:rst)
        {
            
         Dpie.setValue("Correct",s.getCorrect());
          Dpie.setValue("Incorrect",s.getIncorrect());
     Dpie.setValue("UnAttempted",s.getUnattempted());
     System.out.println(""+s.getCorrect()+" "+s.getIncorrect()+" "+s.getUnattempted());
       }
       
 JFreeChart pch=ChartFactory.createPieChart("pie chart",Dpie,true,true,false);
     PiePlot p=(PiePlot)pch.getPlot();
        ChartFrame ch=new ChartFrame("Student Chart Analysis",pch);
        ch.setSize(550,550);
        ch.setResizable(false);
        ch.setLocationRelativeTo(null);
      ch.setVisible(true);
     /* }catch(SQLException ex){
              JOptionPane.showMessageDialog(null,"SQL Error"+ex,"Error!",JOptionPane.ERROR_MESSAGE);
           }
        */
    }//GEN-LAST:event_btnchartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StudentResultAnalysis fr=new  StudentResultAnalysis();
            this.dispose();
            fr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PredictionAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PredictionAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PredictionAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PredictionAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PredictionAnalysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbargraph;
    private javax.swing.JButton btnchart;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAccuracy1;
    private javax.swing.JLabel lblAccuracy2;
    private javax.swing.JLabel lblpreparation1;
    private javax.swing.JLabel lblpreparation2;
    private javax.swing.JLabel lblprogress1;
    private javax.swing.JLabel lblprogress2;
    private javax.swing.JLabel txtHelloMsg;
    // End of variables declaration//GEN-END:variables

    private void setCurrentStatus() {
     try{
         rst=PerformanceDAO.getStudenttestresult(userid,examid);
        System.out.println("hello jp1");
        if(rst.isEmpty()){
               JOptionPane.showMessageDialog(null,"No test given by :"+userid,"Message",JOptionPane.INFORMATION_MESSAGE);
                 System.out.println("hello jp2");
            return;
           }
        System.out.println(""+userid+""+examid);
        for(resultAnalysis s:rst)
        {
       int right=s.getCorrect();
       int wrong=s.getIncorrect();
       int unatt=s.getUnattempted();
       System.out.println(""+right+" "+wrong+" "+unatt);
       
      lblAccuracy1.setText(""+((float)right/(right+wrong))*100+"%");
      lblpreparation1.setText(""+((float)(right+wrong)/(right+wrong+unatt))*100+"%");
       }
        per=PerformanceDAO.getStudentPer(userid,subject);
       if(per.size()==1){
           lblprogress1.setText("-");
           return;
       }
       double p1=0;
       for(int i=0;i<per.size()-1;i++){
           System.out.println(""+per.size()+" "+per.get(i)+" "+per.get(i+1));
          p1=per.get(i+1)-per.get(i);
       }
       if(p1>0){
       lblprogress1.setText("+"+p1+"%");
       }
       else if(p1<0){
            lblprogress1.setText("-"+p1+"%");
       }
       else
            lblprogress1.setText(""+p1+"%");
       
    
     }catch(SQLException ex){
               JOptionPane.showMessageDialog(null,"SQL Error"+ex,"Error!",JOptionPane.ERROR_MESSAGE);
           }
    
    
    }
    
    private void setPredictedStatus(){
       try{
           ArrayList<resultAnalysis> arrs=PerformanceDAO.getStudentRightWrongList(userid, subject);
           if(arrs.isEmpty()){
               lblAccuracy2.setText("--");
               return;
           }
           float f1[]=new float[arrs.size()];
           float f2[]=new float[arrs.size()];
           int i=0;
           for(resultAnalysis s:arrs)
        {
       int right=s.getCorrect();
       int wrong=s.getIncorrect();
       int unatt=s.getUnattempted();
       System.out.println(""+right+" "+wrong+" "+unatt);
       
      f1[i]=((float)right/(right+wrong))*100;
     f2[i]=((float)(right+wrong)/(right+wrong+unatt))*100;
     if(arrs.size()==1){
         lblAccuracy2.setText(""+f1[i]+"%");
         lblpreparation2.setText(""+f2[i]+"%");
         return;
     }
     i++;
      }
     i--;  
     double acc=(f1[i-1]+f1[i])/2;
     double pre=(f2[i-1]+f2[i])/2;
     double signacc=f1[i]-f1[i-1];
     double signpre=f2[i]-f2[i-1];
     for(int j=0;j<=100;j=j+5){
         if(AccuracyValueSet==0){
          if(signacc<0){
              if(acc<=j+5&&acc>j){
                   lblAccuracy2.setText(""+j+"%");
                   AccuracyValueSet=1;
                   System.out.println(" 1 "+j+" ");
              }
         }
          if(signacc>0){
             if(acc<=j+5&&acc>j){
                  lblAccuracy2.setText(""+(j+5)+"%");
                  AccuracyValueSet=1;
                   System.out.println(" 2 "+j+" ");
             }
         }
          if(signacc==0)
         { lblAccuracy2.setText(""+acc+"%"); 
         AccuracyValueSet=1;
           System.out.println(" 3 "+j+" ");
         }
         }
          if(preparationValueSet==0){
     if(signpre<0){
              if(pre<=j+5&&pre>j){
                   lblpreparation2.setText(""+j+"%");
                   preparationValueSet=1;
                    System.out.println(" 4 "+j+" ");
              }
         }
     if(signpre>0){
             if(acc<=j+5&&acc>j){
                   lblpreparation2.setText(""+(j+5)+"%");
                   preparationValueSet=1;
                    System.out.println(" 5 "+j+" ");
             }
         }
     if(signpre==0)
         { lblpreparation2.setText(""+pre+"%"); 
         preparationValueSet=1;
             System.out.println(" 6 "+j+" ");
         }
          }
     }
     
     
    /* if(signacc<0){
         if(acc<=0)
                 lblAccuracy2.setText(""+0+"%");
         else if(acc<=10&&acc>0)
              lblAccuracy2.setText(""+0+"%");
          else if(acc<=20&&acc>10)
              lblAccuracy2.setText(""+10+"%");
         else if(acc<=30&&acc>20)
              lblAccuracy2.setText(""+20+"%");
         else if(acc<=40&&acc>30)
              lblAccuracy2.setText(""+30+"%");
         else if(acc<=50&&acc>40)
              lblAccuracy2.setText(""+40+"%");
         else if(acc<=60&&acc>50)
              lblAccuracy2.setText(""+50+"%");
         else if(acc<=70&&acc>60)
              lblAccuracy2.setText(""+60+"%");
         else if(acc<=80&&acc>70)
              lblAccuracy2.setText(""+70+"%");
         else if(acc<=90&&acc>80)
              lblAccuracy2.setText(""+80+"%");
         else if(acc<=100&&acc>90)
              lblAccuracy2.setText(""+90+"%");
        
     }else if(signacc>0){
         if(acc<=0)
                 lblAccuracy2.setText(""+0+"%");
         else if(acc<=10&&acc>0)
              lblAccuracy2.setText(""+10+"%");
          else if(acc<=20&&acc>10)
              lblAccuracy2.setText(""+20+"%");
         else if(acc<=30&&acc>20)
              lblAccuracy2.setText(""+30+"%");
         else if(acc<=40&&acc>30)
              lblAccuracy2.setText(""+40+"%");
         else if(acc<=50&&acc>40)
              lblAccuracy2.setText(""+50+"%");
         else if(acc<=60&&acc>50)
              lblAccuracy2.setText(""+60+"%");
         else if(acc<=70&&acc>60)
              lblAccuracy2.setText(""+70+"%");
         else if(acc<=80&&acc>70)
              lblAccuracy2.setText(""+80+"%");
         else if(acc<=90&&acc>80)
              lblAccuracy2.setText(""+90+"%");
         else if(acc<=100&&acc>90)
              lblAccuracy2.setText(""+99+"%");
        
     }else
         lblAccuracy2.setText(""+acc+"%");
     
       
       
       
     */  }catch(SQLException ex){
               JOptionPane.showMessageDialog(null,"SQL Error"+ex,"Error!",JOptionPane.ERROR_MESSAGE);
           }
    }
 
    
}
